#!/bin/bash

cd "saida"

mv index.theme ../index.theme_tmp
mv .directory ../.directory_tmp
rm -rf *

for file in "../../default/saida/"*
do
	
	cp -r "$file" .
	
done

mv ../index.theme_tmp index.theme
mv ../.directory_tmp .directory

for file in "../arquivos-para-substituir/"*
do
	
	cp -r "$file" .
	
done

cd ..
./copy-to-temp

#find . -type f -not -name 'index.theme' | xargs rm

exit


